### PR TITLE
Content fixes - Causeway Digital

### PR DESCRIPTION
**Pull request by gbaman**
Fixes for a large collection of open bugs.

### CODE REVIEW

**Comment by gbaman** [comment]
Just to clarify, this PR is not ready for merging just yet, still a few more branches to end up merged in.

**Comment by gbaman** [comment]
That should be all of the changes under the bug fixing project completed, this is ready for review/merge.

**Review by MicahM-MSFT — APPROVED** [review]
Looks good.

**Comment by gbaman** [comment]
@MicahM-MSFT I don't have permission to merge this. Can you merge it?

**Comment by gbaman** [comment]
@MicahM-MSFT can you create a Github Release for this repo to trigger Makecode to recreate the cache on the content?

**Pull request merged**
